version: 2
shared: &shared
  working_directory: ~/riemann
  environment:
    JVM_OPTS: -Xmx3200m
    LEIN_ROOT: nbd
    DATADOG_API_KEY: 9775a026f1ca7d1c6c5af9d94d9595a4
    HIPCHAT_SERVER: api.hipchat.com
    HIPCHAT_API_KEY: 2YotnFZFEjr1zCsicMWpAA
    HIPCHAT_ALERT_ROOM: "#fake"
    LIBRATO_METRICS_USER: "faker"
    LIBRATO_METRICS_API_KEY: "75AFDB82"
    OPSGENIE_SERVICE_KEY: "eb243592-faa2-4ba2-a551q-1afdf565c889"
    OPSGENIE_RECIPIENTS: fakebob
    SLACK_API_KEY: "xoxp-113552566178-113639658309-193597780375-2a4e44931d4827e06f495cbca9d6e7b5"
    SLACK_ALERT_ROOM: "#fake"
    SLACK_ALERT_ACCOUNT: "@fakebob"
    TELEGRAM_API_TOKEN": "1233456789ABC"
    TELEGRAM_CHAT_ID: "1234"
  steps:
    - checkout
    - restore_cache: # restores saved cache if checksum hasn't changed since the last run
        key: riemann-{{ checksum "project.clj" }}
    - run: lein deps
    - save_cache: # generate and store cache in the .m2 directory using a key template
        paths:
          - ~/.m2
          - ~/.lein
        key: riemann-{{ checksum "project.clj" }}
    - run: lein test

jobs:
  jdk11:
    docker: # run the steps with Docker
      - image: circleci/clojure:openjdk-11-lein-2.9.1
    <<: *shared
  jdk8:
    docker: # run the steps with Docker
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    <<: *shared

workflows:
  version: 2
  test:
    jobs:
      - jdk8
      - jdk11
    
